package com.N649000.warrantytracker.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;

import java.math.BigDecimal;
import java.util.Currency;
import java.util.Date;

@Data
@DynamoDBTable(tableName = "product")
public class Product {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String userId;

    @DynamoDBAttribute
    private String name;

    @DynamoDBAttribute
    private String serialNumber;

    @DynamoDBAttribute
    private Date purchasedDate;

    @DynamoDBAttribute
    private Date warrantyExpiryDate;

    @DynamoDBAttribute
    private boolean expiryNotification;

    @DynamoDBAttribute
    private String companyId;

    @DynamoDBAttribute
    private BigDecimal purchasedAmount;

    @DynamoDBAttribute
    private Currency purchasedCurrency;

    @DynamoDBAttribute
    private String notes;
}
